Training_seting:
    model: ResNet101
    training_epoch: 200
    batch_size: 128
    num_workers: 4
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 5.e-4
    warmup_epoch: 10
    dataset: 
        Cifar100 #Options Cifar10, Cifar100, Imagenet
        # Cifar100
        # Imagenet
    dataset_path: data/
    experiment_data_path: Experiment_data/Training_Record/
    weight_path: Weights/